Feature/panda integration
devops-opensource/devops-metrics pull request #3
Opened 2022-05-05 18:49 UTC by Dorian-Vandamme

2022-05-05 19:43 UTC, seb-devops commented on requirements/dev_requirements.txt
> +pandas
Mettons une version précise afin d'éviter des problèmes de compatibilité

2022-05-06 13:27 UTC, sebastien-bernard-dd commented on src/jirascript.py
> +                if(self.epic_key == ""):
self.epic_key == ""
ou
self.epic_key is true

2022-05-06 13:41 UTC, sebastien-bernard-dd requested changes

2022-05-06 13:41 UTC, sebastien-bernard-dd commented on src/jirascript.py
> +                        "&expand=changelog&maxResults=200&startAt="+str(i*max_results),auth=(self.email, self.passwd), headers=self.headers)
jql
field
params 

builq_query(list_field,jql,list_params)

2022-05-06 13:41 UTC, sebastien-bernard-dd commented on src/jirascript.py
> +        for issue in changelogs:
Gestion d'exception permettant de continuer l'opération, mais qui va créer soi un fichier avec output problématique ou qui l'écrit a la console

2022-05-06 13:41 UTC, sebastien-bernard-dd commented on src/jirascript.py
> +                        log = self.create_log(issue,changelog["created"],item["to"],item["toString"])
Si tu ne sais pas ce qu'il y a dans les dictionnaire/list inceptionné, c'est dure de comprendre ce qui est passé

nom_du_param= new_satus_tuple[0]

ou séparé plus

2022-05-06 13:41 UTC, sebastien-bernard-dd commented on src/jirascript.py
> +        elif(issue["fields"].get("customfield_11200") is not None):
Si valeur hardcodé créer un champ avec description de c'est la valeur ex: 

epic_link_custom_field = "customfield_11200"

2022-05-06 13:41 UTC, sebastien-bernard-dd commented on src/jirascript.py
> +        project_list_response = requests.get(self.jira_adress+"/rest/api/2/project",auth=(self.email, self.passwd), headers=self.headers)
Gestion plus élaboré avec utilitaire

2022-05-06 13:41 UTC, sebastien-bernard-dd commented on src/jirascript.py
> +        for project in project_list:
Utiliser les fonctions lambdas pour chercher l'éléments

2022-05-06 13:41 UTC, sebastien-bernard-dd commented on src/jirascript.py
> +    config.read('../config.cfg')
Mettre dans une fonction

2022-05-06 13:41 UTC, sebastien-bernard-dd commented on src/jirascript.py
>      if(output_type == "csv"):
Gérer les import différents avec des objets

2022-05-06 13:50 UTC, merged